name: flutter_yandex_ads
description: Yandex Ads support for flutter applications.
version: 1.0.5
homepage: https://gitflic.ru/project/getapp/getapp-yandexads-flutter

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^17.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.kovardin.flutter_yandex_ads
        pluginClass: FlutterYandexAdsPlugin
      ios:
        pluginClass: FlutterYandexAdsPlugin

