# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  yandex:
    cmds:
      - flutter pub run pigeon
        --input pigeons/yandex.dart

  banner:
    cmds:
      - flutter pub run pigeon
        --input pigeons/banner.dart

  native:
    cmds:
      - flutter pub run pigeon
        --input pigeons/native.dart

  interstitial:
    cmds:
      - flutter pub run pigeon
        --input pigeons/interstitial.dart

  rewarded:
    cmds:
      - flutter pub run pigeon
        --input pigeons/rewarded.dart

  appopen:
    cmds:
      - flutter pub run pigeon
        --input pigeons/appopen.dart

  pigeons:
    cmds:
      - task: yandex
      - task: banner
      - task: native
      - task: interstitial
      - task: rewarded
      - task: appopen

  release:
    cmds:
      - flutter pub publish

