// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class BannerError;
@class BannerImpression;

@interface BannerError : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    description:(NSString *)description;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy) NSString * description;
@end

@interface BannerImpression : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithData:(NSString *)data;
@property(nonatomic, copy) NSString * data;
@end

/// The codec used by YandexAdsBanner.
NSObject<FlutterMessageCodec> *YandexAdsBannerGetCodec(void);

@protocol YandexAdsBanner
- (void)makeId:(NSString *)id width:(NSNumber *)width height:(NSNumber *)height error:(FlutterError *_Nullable *_Nonnull)error;
- (void)loadId:(NSString *)id error:(FlutterError *_Nullable *_Nonnull)error;
- (void)onAdLoadedId:(NSString *)id completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onAdFailedToLoadId:(NSString *)id completion:(void (^)(BannerError *_Nullable, FlutterError *_Nullable))completion;
- (void)onAdClickedId:(NSString *)id completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onLeftApplicationId:(NSString *)id completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onReturnedToApplicationId:(NSString *)id completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onImpressionId:(NSString *)id completion:(void (^)(BannerImpression *_Nullable, FlutterError *_Nullable))completion;
@end

extern void YandexAdsBannerSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YandexAdsBanner> *_Nullable api);

NS_ASSUME_NONNULL_END
