// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Banner.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface BannerError ()
+ (BannerError *)fromList:(NSArray *)list;
+ (nullable BannerError *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface BannerImpression ()
+ (BannerImpression *)fromList:(NSArray *)list;
+ (nullable BannerImpression *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation BannerError
+ (instancetype)makeWithCode:(NSNumber *)code
    description:(NSString *)description {
  BannerError* pigeonResult = [[BannerError alloc] init];
  pigeonResult.code = code;
  pigeonResult.description = description;
  return pigeonResult;
}
+ (BannerError *)fromList:(NSArray *)list {
  BannerError *pigeonResult = [[BannerError alloc] init];
  pigeonResult.code = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.code != nil, @"");
  pigeonResult.description = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.description != nil, @"");
  return pigeonResult;
}
+ (nullable BannerError *)nullableFromList:(NSArray *)list {
  return (list) ? [BannerError fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.code ?: [NSNull null]),
    (self.description ?: [NSNull null]),
  ];
}
@end

@implementation BannerImpression
+ (instancetype)makeWithData:(NSString *)data {
  BannerImpression* pigeonResult = [[BannerImpression alloc] init];
  pigeonResult.data = data;
  return pigeonResult;
}
+ (BannerImpression *)fromList:(NSArray *)list {
  BannerImpression *pigeonResult = [[BannerImpression alloc] init];
  pigeonResult.data = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.data != nil, @"");
  return pigeonResult;
}
+ (nullable BannerImpression *)nullableFromList:(NSArray *)list {
  return (list) ? [BannerImpression fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.data ?: [NSNull null]),
  ];
}
@end

@interface YandexAdsBannerCodecReader : FlutterStandardReader
@end
@implementation YandexAdsBannerCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [BannerError fromList:[self readValue]];
    case 129: 
      return [BannerImpression fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface YandexAdsBannerCodecWriter : FlutterStandardWriter
@end
@implementation YandexAdsBannerCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[BannerError class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[BannerImpression class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface YandexAdsBannerCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation YandexAdsBannerCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[YandexAdsBannerCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[YandexAdsBannerCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *YandexAdsBannerGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    YandexAdsBannerCodecReaderWriter *readerWriter = [[YandexAdsBannerCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void YandexAdsBannerSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YandexAdsBanner> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.make"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(makeId:width:height:error:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(makeId:width:height:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_width = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_height = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        [api makeId:arg_id width:arg_width height:arg_height error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.load"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(loadId:error:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(loadId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api loadId:arg_id error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.onAdLoaded"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onAdLoadedId:completion:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(onAdLoadedId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api onAdLoadedId:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.onAdFailedToLoad"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onAdFailedToLoadId:completion:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(onAdFailedToLoadId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api onAdFailedToLoadId:arg_id completion:^(BannerError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.onAdClicked"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onAdClickedId:completion:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(onAdClickedId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api onAdClickedId:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.onLeftApplication"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onLeftApplicationId:completion:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(onLeftApplicationId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api onLeftApplicationId:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.onReturnedToApplication"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onReturnedToApplicationId:completion:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(onReturnedToApplicationId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api onReturnedToApplicationId:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsBanner.onImpression"
        binaryMessenger:binaryMessenger
        codec:YandexAdsBannerGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onImpressionId:completion:)], @"YandexAdsBanner api (%@) doesn't respond to @selector(onImpressionId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api onImpressionId:arg_id completion:^(BannerImpression *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
