// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Interstitial.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface InterstitialError ()
+ (InterstitialError *)fromList:(NSArray *)list;
+ (nullable InterstitialError *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface InterstitialImpression ()
+ (InterstitialImpression *)fromList:(NSArray *)list;
+ (nullable InterstitialImpression *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation InterstitialError
+ (instancetype)makeWithCode:(NSNumber *)code
    description:(NSString *)description {
  InterstitialError* pigeonResult = [[InterstitialError alloc] init];
  pigeonResult.code = code;
  pigeonResult.description = description;
  return pigeonResult;
}
+ (InterstitialError *)fromList:(NSArray *)list {
  InterstitialError *pigeonResult = [[InterstitialError alloc] init];
  pigeonResult.code = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.code != nil, @"");
  pigeonResult.description = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.description != nil, @"");
  return pigeonResult;
}
+ (nullable InterstitialError *)nullableFromList:(NSArray *)list {
  return (list) ? [InterstitialError fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.code ?: [NSNull null]),
    (self.description ?: [NSNull null]),
  ];
}
@end

@implementation InterstitialImpression
+ (instancetype)makeWithData:(NSString *)data {
  InterstitialImpression* pigeonResult = [[InterstitialImpression alloc] init];
  pigeonResult.data = data;
  return pigeonResult;
}
+ (InterstitialImpression *)fromList:(NSArray *)list {
  InterstitialImpression *pigeonResult = [[InterstitialImpression alloc] init];
  pigeonResult.data = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.data != nil, @"");
  return pigeonResult;
}
+ (nullable InterstitialImpression *)nullableFromList:(NSArray *)list {
  return (list) ? [InterstitialImpression fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.data ?: [NSNull null]),
  ];
}
@end

NSObject<FlutterMessageCodec> *YandexAdsInterstitialGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void YandexAdsInterstitialSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YandexAdsInterstitial> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsInterstitial.make"
        binaryMessenger:binaryMessenger
        codec:YandexAdsInterstitialGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(makeId:error:)], @"YandexAdsInterstitial api (%@) doesn't respond to @selector(makeId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api makeId:arg_id error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsInterstitial.load"
        binaryMessenger:binaryMessenger
        codec:YandexAdsInterstitialGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(loadId:error:)], @"YandexAdsInterstitial api (%@) doesn't respond to @selector(loadId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api loadId:arg_id error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.flutter_yandex_ads.YandexAdsInterstitial.show"
        binaryMessenger:binaryMessenger
        codec:YandexAdsInterstitialGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(showId:error:)], @"YandexAdsInterstitial api (%@) doesn't respond to @selector(showId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api showId:arg_id error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FlutterYandexAdsInterstitialCodecReader : FlutterStandardReader
@end
@implementation FlutterYandexAdsInterstitialCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [InterstitialError fromList:[self readValue]];
    case 129: 
      return [InterstitialImpression fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FlutterYandexAdsInterstitialCodecWriter : FlutterStandardWriter
@end
@implementation FlutterYandexAdsInterstitialCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[InterstitialError class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[InterstitialImpression class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FlutterYandexAdsInterstitialCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FlutterYandexAdsInterstitialCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FlutterYandexAdsInterstitialCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FlutterYandexAdsInterstitialCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FlutterYandexAdsInterstitialGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FlutterYandexAdsInterstitialCodecReaderWriter *readerWriter = [[FlutterYandexAdsInterstitialCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface FlutterYandexAdsInterstitial ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FlutterYandexAdsInterstitial

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onAdLoadedId:(NSString *)arg_id completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.flutter_yandex_ads.FlutterYandexAdsInterstitial.onAdLoaded"
      binaryMessenger:self.binaryMessenger
      codec:FlutterYandexAdsInterstitialGetCodec()];
  [channel sendMessage:@[arg_id ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onAdFailedToLoadId:(NSString *)arg_id err:(InterstitialError *)arg_err completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.flutter_yandex_ads.FlutterYandexAdsInterstitial.onAdFailedToLoad"
      binaryMessenger:self.binaryMessenger
      codec:FlutterYandexAdsInterstitialGetCodec()];
  [channel sendMessage:@[arg_id ?: [NSNull null], arg_err ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onAdFailedToShowId:(NSString *)arg_id err:(InterstitialError *)arg_err completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.flutter_yandex_ads.FlutterYandexAdsInterstitial.onAdFailedToShow"
      binaryMessenger:self.binaryMessenger
      codec:FlutterYandexAdsInterstitialGetCodec()];
  [channel sendMessage:@[arg_id ?: [NSNull null], arg_err ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onAdShownId:(NSString *)arg_id completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.flutter_yandex_ads.FlutterYandexAdsInterstitial.onAdShown"
      binaryMessenger:self.binaryMessenger
      codec:FlutterYandexAdsInterstitialGetCodec()];
  [channel sendMessage:@[arg_id ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onAdDismissedId:(NSString *)arg_id completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.flutter_yandex_ads.FlutterYandexAdsInterstitial.onAdDismissed"
      binaryMessenger:self.binaryMessenger
      codec:FlutterYandexAdsInterstitialGetCodec()];
  [channel sendMessage:@[arg_id ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onAdClickedId:(NSString *)arg_id completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.flutter_yandex_ads.FlutterYandexAdsInterstitial.onAdClicked"
      binaryMessenger:self.binaryMessenger
      codec:FlutterYandexAdsInterstitialGetCodec()];
  [channel sendMessage:@[arg_id ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onImpressionId:(NSString *)arg_id data:(InterstitialImpression *)arg_data completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.flutter_yandex_ads.FlutterYandexAdsInterstitial.onImpression"
      binaryMessenger:self.binaryMessenger
      codec:FlutterYandexAdsInterstitialGetCodec()];
  [channel sendMessage:@[arg_id ?: [NSNull null], arg_data ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

