// Autogenerated from Pigeon (v14.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct RewardedError {
  var code: Int64
  var description: String

  static func fromList(_ list: [Any?]) -> RewardedError? {
    let code = list[0] is Int64 ? list[0] as! Int64 : Int64(list[0] as! Int32)
    let description = list[1] as! String

    return RewardedError(
      code: code,
      description: description
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      description,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RewardedImpression {
  var data: String

  static func fromList(_ list: [Any?]) -> RewardedImpression? {
    let data = list[0] as! String

    return RewardedImpression(
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      data,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RewardedEvent {
  var amount: Int64
  var type: String

  static func fromList(_ list: [Any?]) -> RewardedEvent? {
    let amount = list[0] is Int64 ? list[0] as! Int64 : Int64(list[0] as! Int32)
    let type = list[1] as! String

    return RewardedEvent(
      amount: amount,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      amount,
      type,
    ]
  }
}

private class YandexAdsRewardedCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return RewardedError.fromList(self.readValue() as! [Any?])
      case 129:
        return RewardedEvent.fromList(self.readValue() as! [Any?])
      case 130:
        return RewardedImpression.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class YandexAdsRewardedCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RewardedError {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? RewardedEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? RewardedImpression {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class YandexAdsRewardedCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return YandexAdsRewardedCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return YandexAdsRewardedCodecWriter(data: data)
  }
}

class YandexAdsRewardedCodec: FlutterStandardMessageCodec {
  static let shared = YandexAdsRewardedCodec(readerWriter: YandexAdsRewardedCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol YandexAdsRewarded {
  func make(id: String) throws
  func load(id: String) throws
  func show(id: String) throws
  func onAdLoaded(id: String, completion: @escaping (Result<Void, Error>) -> Void)
  func onAdFailedToLoad(id: String, completion: @escaping (Result<RewardedError, Error>) -> Void)
  func onAdFailedToShow(id: String, completion: @escaping (Result<RewardedError, Error>) -> Void)
  func onAdShown(id: String, completion: @escaping (Result<Void, Error>) -> Void)
  func onAdDismissed(id: String, completion: @escaping (Result<Void, Error>) -> Void)
  func onAdClicked(id: String, completion: @escaping (Result<Void, Error>) -> Void)
  func onImpression(id: String, completion: @escaping (Result<RewardedImpression, Error>) -> Void)
  func onRewarded(id: String, completion: @escaping (Result<RewardedEvent, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class YandexAdsRewardedSetup {
  /// The codec used by YandexAdsRewarded.
  static var codec: FlutterStandardMessageCodec { YandexAdsRewardedCodec.shared }
  /// Sets up an instance of `YandexAdsRewarded` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: YandexAdsRewarded?) {
    let makeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.make", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      makeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.make(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      makeChannel.setMessageHandler(nil)
    }
    let loadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.load", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.load(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadChannel.setMessageHandler(nil)
    }
    let showChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.show", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.show(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showChannel.setMessageHandler(nil)
    }
    let onAdLoadedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onAdLoaded", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAdLoadedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onAdLoaded(id: idArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onAdLoadedChannel.setMessageHandler(nil)
    }
    let onAdFailedToLoadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onAdFailedToLoad", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAdFailedToLoadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onAdFailedToLoad(id: idArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onAdFailedToLoadChannel.setMessageHandler(nil)
    }
    let onAdFailedToShowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onAdFailedToShow", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAdFailedToShowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onAdFailedToShow(id: idArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onAdFailedToShowChannel.setMessageHandler(nil)
    }
    let onAdShownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onAdShown", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAdShownChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onAdShown(id: idArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onAdShownChannel.setMessageHandler(nil)
    }
    let onAdDismissedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onAdDismissed", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAdDismissedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onAdDismissed(id: idArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onAdDismissedChannel.setMessageHandler(nil)
    }
    let onAdClickedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onAdClicked", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAdClickedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onAdClicked(id: idArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onAdClickedChannel.setMessageHandler(nil)
    }
    let onImpressionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onImpression", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onImpressionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onImpression(id: idArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onImpressionChannel.setMessageHandler(nil)
    }
    let onRewardedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_yandex_ads.YandexAdsRewarded.onRewarded", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onRewardedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.onRewarded(id: idArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      onRewardedChannel.setMessageHandler(nil)
    }
  }
}
