// Autogenerated from Pigeon (v4.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


///The codec used by YandexAdsApi.
NSObject<FlutterMessageCodec> *YandexAdsApiGetCodec(void);

@protocol YandexAdsApi
- (void)initializeWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void YandexAdsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YandexAdsApi> *_Nullable api);

NS_ASSUME_NONNULL_END
